### ISSUE TITLE
add 2024-01-29 exam to "Data Science" folder

### ISSUE THREAD

**Issue by LilloBarilotto** [Guray00/ComputerEngineeringPoliTO#1]
https://github.com/Guray00/ComputerEngineeringPoliTO/tree/main/II%20-%20MAGISTRALE/I%20-%20%5B01SQMOV%5D%20Data%20Science%20e%20Tecnologie%20per%20le%20Basi%20di%20Dati/Esami

add the attached file if possible
[2024-01-29.pdf](https://github.com/Guray00/ComputerEngineeringPoliTO/files/14229673/2024-01-29.pdf)

**Comment by Guray00** [comment]
Thank you, I'm gonna add it right now!
